# Generated by Django 5.1.6 on 2025-05-19 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('username', models.EmailField(max_length=100)),
                ('price_lower_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_upper_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='item_pictures/')),
                ('sold', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('username', models.EmailField(max_length=100)),
                ('price_lower_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_upper_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=False)),
                ('buyer_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('room_sold', models.BooleanField(default=False)),
                ('results', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='sales.item')),
                ('raiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raiser', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
