# Generated by Django 5.1.6 on 2025-05-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_lower_bound',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_upper_bound',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='need',
            name='price_lower_bound',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='need',
            name='price_upper_bound',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
