# Generated by Django 5.1.6 on 2025-05-26 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='邮箱必须是清华大学邮箱(@mails.tsinghua.edu.cn)', regex='^[a-zA-Z0-9._%+-]+@mails\\.tsinghua\\.edu\\.cn$')]),
        ),
    ]
